SH_TILE_SIZE = 16

# general
CAPTION = "GPD-4X"
FPS = 60
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 1680, 1050  # 0, 0 == fullscreen
BG_COLOR = "black"
TILE_SIZE = 32
ACTIVATE_TEST_GRID = False

SELECTION_BOX_COLOR = "red"
SELECTION_BOX_WIDTH = 1

# Camera
CAMERA_SPEED = 100
ACTIVATE_SCROLLING_BORDERS = True

assert TILE_SIZE % SH_TILE_SIZE == 0
